### ISSUE TITLE
Error when running the extending example on Ruby 2.3

### ISSUE THREAD

**Issue by thedrow** [rom-rb/rom-http#21]
I'm talking about http://www.rubydoc.info/gems/rom-http#Extending
https://github.com/rom-rb/rom-support/pull/9 should fix this but there might be something wrong with the example itself.

```
/Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rom-2.0.0/lib/rom/plugins/relation/view.rb:76:in `view': undefined method `arity' for nil:NilClass (NoMethodError)
    from /Volumes/fiverr_dev/restfull-client/lib/rom_adapter.rb:30:in `<class:Relation>'
    from /Volumes/fiverr_dev/restfull-client/lib/rom_adapter.rb:22:in `<module:RestfullClientAdapter>'
    from /Volumes/fiverr_dev/restfull-client/lib/rom_adapter.rb:5:in `<module:ROM>'
    from /Volumes/fiverr_dev/restfull-client/lib/rom_adapter.rb:4:in `<top (required)>'
    from /Volumes/fiverr_dev/restfull-client/spec/support/models.rb:2:in `require'
    from /Volumes/fiverr_dev/restfull-client/spec/support/models.rb:2:in `<top (required)>'
    from /Volumes/fiverr_dev/restfull-client/spec/spec_helper.rb:6:in `load'
    from /Volumes/fiverr_dev/restfull-client/spec/spec_helper.rb:6:in `block in <top (required)>'
    from /Volumes/fiverr_dev/restfull-client/spec/spec_helper.rb:6:in `each'
    from /Volumes/fiverr_dev/restfull-client/spec/spec_helper.rb:6:in `<top (required)>'
    from /Users/omer.katz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/omer.katz/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `block in requires='
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `each'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration.rb:1394:in `requires='
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:111:in `each'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/configuration_options.rb:21:in `configure'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:99:in `setup'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:86:in `run'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/invocations.rb:23:in `call'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:69:in `run'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/gems/rspec-core-3.5.3/exe/rspec:4:in `<top (required)>'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/bin/rspec:23:in `load'
    from /Users/omer.katz/.rvm/gems/ruby-2.2.2@restfull_client/bin/rspec:23:in `<top (required)>'
    from -e:1:in `load'
    from -e:1:in `<main>'
```

**Comment by AMHOL** [comment]
No syntax errors for me here, how did you get this to happen?
